#!/bin/bash
#
# 2022-01-22
# kareem@missoumi.org
#
# Upload. Skip and return storage Id if previously uploaded.
#
# Copyright (c) 2022, Kareem Missoumi
# All rights reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#


# avoid duplicate uploads
printf "\n"
# check for environment variable if parameter is not provided
[[ -z ${1} ]] || appFile=${1}
[[ ! -f ${appFile} ]] && printf "Provide the fully qualified path to an app as the 1st parameter.\n" && exit 2
[[ -z ${2} ]] && appName=${appFile##*/} || appName=${2}

appCheckSum=$(shasum -a 256 ${appFile} |cut -c 1-65)
timeStamp=$(date +"%Y-%m-%d_%H%M%S_%s")
scriptPath="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
quickSauceHome=$(echo "${scriptPath%/*}")
baseDir="${quickSauceHome}/data/api/storage/${timeStamp}"

[[ -z ${SAUCE_DC} ]] && SAUCE_DC="us-west-1"
protoHost="https://api.${SAUCE_DC}.saucelabs.com"
userAuth="${SAUCE_USERNAME}:${SAUCE_ACCESS_KEY}"

# call the storage api
# ask jq to clean up mickey mouse response
r=$(curl --silent --user ${userAuth} \
  --request GET "${protoHost}/v1/storage/files?sha256=${appCheckSum}" \
  | jq  '.items[]|del(.metadata.icon)')

mkdir -p ${baseDir}
printf "%s" ${r} |jq > ${baseDir}/storageQueryResponse.json

[[ -n ${r} ]] && printf 'App found. Skipping upload.\n' && fileId=$(jq --raw-output '.id' <<< ${r}) && printf 'fileId=%s\n' ${fileId} && exit 0


printf "Uploading app..."
r=$(curl --silent --user ${userAuth} \
  --write-out "\n%{http_code}" \
  --request POST ${protoHost}/v1/storage/upload \
  --form payload=@"${appFile}" \
  --form name="${appName}" \
  --form description="My Demo App")


httpStatus="${r##*$'\n'}"
r="${r%????}"

printf "%s" ${r} |jq '.item|del(.metadata.icon)' > ${baseDir}/storageUploadResponse.json
fileId=$(jq '.id' ${baseDir}/storageUploadResponse.json)

printf 'task complete.\nstatus=%s\nresponse output path: %s\n' ${httpStatus} ${baseDir}
printf 'fileId=%s\n' ${fileId}

exit 0



# disable instrumentation

--data-raw '{"settings":{"resigning":{"image_injection":false}}}'\

curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location \
--request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
--form 'payload=@"g16K4P8IX/iOS.RealDevice.SauceLabs.Mobile.Sample.app.2.7.1.ipa"' \
--form 'name="iOS.RealDevice.SauceLabs.Mobile.Sample.app.2.7.1.ipa"' \
--form 'description="iOS Test App v3"'